name: ros2-jazzy
version: '3'

services:
  desktop:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-webtop-jazzy
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=ros2
      - PASSWORD=password
      - SUBFOLDER=/ #optional
      - TITLE=ROS2 jazz #optional
    #volumes:
      #- /path/to/data:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3022:22
      - 3000:3000
      - 3001:3001
    shm_size: "1gb" #optional
    restart: unless-stopped